services:
  db_electre:
    image: postgres:14-alpine
    volumes:
      - postgres_data_electre_mor:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-electremor}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change_me}
      POSTGRES_DB: ${POSTGRES_DB:-electremor}

  electre_mor:
    build:
      context: .
      dockerfile: electre_mor/Dockerfile
    entrypoint: './entrypoint_electre.sh'
    expose:
      - 80
    environment:
      SQL_ENGINE: ${SQL_ENGINE:-django.db.backends.postgresql}
      SQL_HOST: ${SQL_HOST:-db_electre}
      SQL_PORT: ${SQL_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER:-electremor}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change_me}
      POSTGRES_DB: ${POSTGRES_DB:-electremor}
      SECRET_KEY: ${SECRET_KEY:-change_me}
      DEBUG: ${DEBUG:-1}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1,coolify.drg.ink,electremor.drg.ink,electremor-dev.drg.ink}
    depends_on:
      - db_electre
    labels:
      - traefik.enable=true
      - traefik.http.routers.electremor.rule=Host(`${TRAEFIK_HOST:-electremor.drg.ink}`)
      - traefik.http.routers.electremor.entrypoints=web,websecure
      - traefik.http.routers.electremor.tls=true
      - traefik.http.services.electremor.loadbalancer.server.port=80

volumes:
  postgres_data_electre_mor:
