# Generated by Django 3.1.2 on 2020-10-24 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('monotonico', models.IntegerField(choices=[(1, 'lucro'), (2, 'custo')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='AlternativaCriterio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(null=True)),
                ('alternativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativa', to='app.alternativa')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterio', to='app.criterio')),
            ],
        ),
    ]
