# Generated by Django 3.0.8 on 2021-05-04 03:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('numerico', models.BooleanField(default=False)),
                ('monotonico', models.IntegerField(choices=[(1, 'lucro'), (2, 'custo')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.TextField(max_length=400)),
                ('qtde_classes', models.IntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('qtde_criterios', models.IntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('qtde_alternativas', models.IntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('qtde_decisores', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('lamb', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Decisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('projeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisores', to='core.Projeto')),
            ],
        ),
        migrations.CreateModel(
            name='CriterioParametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.FloatField()),
                ('q', models.FloatField()),
                ('v', models.FloatField()),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterioparametro', to='core.Criterio')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterioparametro', to='core.Projeto')),
            ],
        ),
        migrations.AddField(
            model_name='criterio',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='core.Projeto'),
        ),
        migrations.CreateModel(
            name='AvaliacaoCriterios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(default=0)),
                ('criterioA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterioA', to='core.Criterio')),
                ('criterioB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterioB', to='core.Criterio')),
                ('decisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacaocriterios', to='core.Decisor')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacaocriterios', to='core.Projeto')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoAlternativas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(null=True)),
                ('alternativaA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativaA', to='core.Alternativa')),
                ('alternativaB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativaB', to='core.Alternativa')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacaoalternativas', to='core.Criterio')),
                ('decisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacaoalternativas', to='core.Decisor')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacaoalternativas', to='core.Projeto')),
            ],
        ),
        migrations.CreateModel(
            name='AlternativaCriterio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(null=True)),
                ('alternativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativacriterio', to='core.Alternativa')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativacriterio', to='core.Criterio')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativacriterios', to='core.Projeto')),
            ],
        ),
        migrations.AddField(
            model_name='alternativa',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='core.Projeto'),
        ),
        migrations.AddConstraint(
            model_name='decisor',
            constraint=models.UniqueConstraint(fields=('nome', 'projeto'), name='unique_decisor'),
        ),
        migrations.AddConstraint(
            model_name='criterio',
            constraint=models.UniqueConstraint(fields=('nome', 'projeto'), name='unique_criterio'),
        ),
        migrations.AddConstraint(
            model_name='alternativa',
            constraint=models.UniqueConstraint(fields=('nome', 'projeto'), name='unique_alternativa'),
        ),
    ]
