# Generated by Django 3.0.8 on 2021-05-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaocriterios',
            name='nota',
            field=models.IntegerField(default=0),
        ),
    ]
