# Generated by Django 3.0.8 on 2021-05-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterio',
            name='numerico',
            field=models.BooleanField(default=True),
        ),
    ]
