# Generated by Django 3.0.8 on 2021-12-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210508_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterio',
            name='monotonico',
            field=models.IntegerField(choices=[(1, 'increasing'), (2, 'decreasing')], default=1),
        ),
    ]
