# Generated by Django 3.0.8 on 2021-12-13 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211213_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
