# Generated by Django 5.2.3 on 2026-05-15 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_resultado_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='lamb',
            field=models.FloatField(default=0.75, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
